"""add selected_primary and selected_relevant columns

Revision ID: 6817163c4b32
Revises: 
Create Date: 2026-01-08 18:11:49.472718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6817163c4b32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('selected_primary', sa.String(length=255), nullable=True))
    op.add_column('cases', sa.Column('selected_relevant', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'selected_relevant')
    op.drop_column('cases', 'selected_primary')
    # ### end Alembic commands ###
